package service

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// UnitName is the systemd unit tailproxy installs.
const UnitName = "tailproxy.service"

// RelayUnitName is the unit `tailproxy service install --relay` installs.
const RelayUnitName = "tailproxy-relay.service"

// UnitOptions describes a systemd unit for `tailproxy run`, or with Relay
// for `tailproxy relay`.
type UnitOptions struct {
	Exe      string // absolute path of the tailproxy binary
	Config   string // absolute path of the config file (not used by Relay)
	StateDir string // absolute state directory (holds the token file)
	User     string // system units: account to run as ("" = root)
	UserUnit bool   // systemctl --user unit instead of a system unit

	Relay        bool   // run `tailproxy relay` instead of `tailproxy run`
	RelayListen  string // relay: --listen (empty: the Tailscale IPv4, port 1081)
	AllowPrivate bool   // relay: --allow-private
}

// Name is the unit's file name.
func (o UnitOptions) Name() string {
	if o.Relay {
		return RelayUnitName
	}
	return UnitName
}

// Unit renders the unit file. The service runs `tailproxy run` (or `tailproxy
// relay`) in the foreground with Type=notify, so systemd considers it
// started only once it is listening.
func Unit(o UnitOptions) (string, error) {
	paths := map[string]string{"exe": o.Exe, "state dir": o.StateDir}
	if !o.Relay {
		paths["config"] = o.Config
	}
	for name, p := range paths {
		if !filepath.IsAbs(p) {
			return "", fmt.Errorf("systemd unit: %s path %q must be absolute", name, p)
		}
		if strings.ContainsAny(p, "\n\"\\%$") {
			return "", fmt.Errorf("systemd unit: %s path %q contains characters that need escaping", name, p)
		}
	}
	if strings.ContainsAny(o.RelayListen, " \t\n\"\\%$'") {
		return "", fmt.Errorf("systemd unit: listen address %q contains characters that need escaping", o.RelayListen)
	}
	if o.UserUnit && o.User != "" {
		return "", fmt.Errorf("systemd unit: a user unit cannot set User=")
	}

	var b strings.Builder
	b.WriteString("# Generated by `tailproxy service install`.\n")
	b.WriteString("[Unit]\n")
	if o.Relay {
		b.WriteString("Description=tailproxy relay - egress for tailproxy clients over the tailnet\n")
	} else {
		b.WriteString("Description=tailproxy - Tailscale exit-node routing proxy\n")
	}
	b.WriteString("Documentation=https://github.com/NannaOlympicBroadcast/tailproxy\n")
	if !o.UserUnit {
		b.WriteString("Wants=network-online.target\n")
		if o.Relay {
			// The relay listens on the Tailscale address, so start after tailscaled.
			b.WriteString("After=network-online.target tailscaled.service\n")
		} else {
			b.WriteString("After=network-online.target\n")
		}
	}
	b.WriteString("\n[Service]\n")
	b.WriteString("Type=notify\n")
	b.WriteString("NotifyAccess=main\n")
	if o.Relay {
		fmt.Fprintf(&b, "ExecStart=%s relay --state-dir %s", quoteArg(o.Exe), quoteArg(o.StateDir))
		if o.RelayListen != "" {
			fmt.Fprintf(&b, " --listen %s", o.RelayListen)
		}
		if o.AllowPrivate {
			b.WriteString(" --allow-private")
		}
		b.WriteString("\n")
		b.WriteString("Restart=always\nRestartSec=3\n")
		// Waits up to a minute for tailscaled to bring up the Tailscale address.
		b.WriteString("TimeoutStartSec=90\nTimeoutStopSec=15\n")
	} else {
		// Optional secrets such as TS_AUTHKEY; "-" means the file may be absent.
		fmt.Fprintf(&b, "EnvironmentFile=-%s\n", quoteArg(filepath.Join(o.StateDir, "tailproxy.env")))
		fmt.Fprintf(&b, "ExecStart=%s run -c %s --state-dir %s\n", quoteArg(o.Exe), quoteArg(o.Config), quoteArg(o.StateDir))
		// With capture.mode tproxy, a crash would leave nft rules sending
		// traffic to a dead listener; remove them whenever the service
		// stops ("-": fine when capture was not used or not root).
		fmt.Fprintf(&b, "ExecStopPost=-%s capture down\n", quoteArg(o.Exe))
		b.WriteString("Restart=on-failure\nRestartSec=3\n")
		b.WriteString("TimeoutStartSec=30\nTimeoutStopSec=15\n")
	}
	if !o.UserUnit {
		if o.User != "" && o.User != "root" {
			fmt.Fprintf(&b, "User=%s\n", o.User)
		}
		// Hardening. The config directory must stay writable: the panel saves
		// rules into it (temp file + rename, plus a .bak copy).
		b.WriteString("NoNewPrivileges=yes\n")
		b.WriteString("PrivateTmp=yes\n")
		b.WriteString("ProtectSystem=strict\n")
		b.WriteString("ProtectHome=read-only\n")
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", strings.Join(rwPaths(o), " "))
		b.WriteString("ProtectKernelTunables=yes\nProtectKernelModules=yes\nProtectControlGroups=yes\n")
		b.WriteString("RestrictSUIDSGID=yes\nLockPersonality=yes\n")
	} else {
		b.WriteString("Environment=TAILPROXY_USER_UNIT=1\n")
		b.WriteString("NoNewPrivileges=yes\n")
	}
	b.WriteString("\n[Install]\n")
	if o.UserUnit {
		b.WriteString("WantedBy=default.target\n")
	} else {
		b.WriteString("WantedBy=multi-user.target\n")
	}
	return b.String(), nil
}

// rwPaths returns the state dir and config dir, deduplicated and sorted.
func rwPaths(o UnitOptions) []string {
	set := map[string]bool{o.StateDir: true}
	if !o.Relay {
		set[filepath.Dir(o.Config)] = true
	}
	var out []string
	for p := range set {
		out = append(out, quoteArg(p))
	}
	sort.Strings(out)
	return out
}

// quoteArg quotes a path for a systemd command line if it contains spaces.
func quoteArg(s string) string {
	if strings.ContainsAny(s, " \t'") {
		return `"` + s + `"`
	}
	return s
}
