package service

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// UnitName is the systemd unit tailproxy installs.
const UnitName = "tailproxy.service"

// UnitOptions describes a systemd unit for `tailproxy run`.
type UnitOptions struct {
	Exe      string // absolute path of the tailproxy binary
	Config   string // absolute path of the config file
	StateDir string // absolute state directory (holds the token file)
	User     string // system units: account to run as ("" = root)
	UserUnit bool   // systemctl --user unit instead of a system unit
}

// Unit renders the unit file. The service runs `tailproxy run` in the
// foreground with Type=notify, so systemd considers it started only once
// the panel is listening.
func Unit(o UnitOptions) (string, error) {
	for name, p := range map[string]string{"exe": o.Exe, "config": o.Config, "state dir": o.StateDir} {
		if !filepath.IsAbs(p) {
			return "", fmt.Errorf("systemd unit: %s path %q must be absolute", name, p)
		}
		if strings.ContainsAny(p, "\n\"\\%$") {
			return "", fmt.Errorf("systemd unit: %s path %q contains characters that need escaping", name, p)
		}
	}
	if o.UserUnit && o.User != "" {
		return "", fmt.Errorf("systemd unit: a user unit cannot set User=")
	}

	var b strings.Builder
	b.WriteString("# Generated by `tailproxy service install`.\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=tailproxy - Tailscale exit-node routing proxy\n")
	b.WriteString("Documentation=https://github.com/NannaOlympicBroadcast/tailproxy\n")
	if !o.UserUnit {
		b.WriteString("Wants=network-online.target\nAfter=network-online.target\n")
	}
	b.WriteString("\n[Service]\n")
	b.WriteString("Type=notify\n")
	b.WriteString("NotifyAccess=main\n")
	fmt.Fprintf(&b, "ExecStart=%s run -c %s --state-dir %s\n", quoteArg(o.Exe), quoteArg(o.Config), quoteArg(o.StateDir))
	b.WriteString("Restart=on-failure\nRestartSec=3\n")
	b.WriteString("TimeoutStartSec=30\nTimeoutStopSec=15\n")
	if !o.UserUnit {
		if o.User != "" && o.User != "root" {
			fmt.Fprintf(&b, "User=%s\n", o.User)
		}
		// Hardening. The config directory must stay writable: the panel saves
		// rules into it (temp file + rename, plus a .bak copy).
		b.WriteString("NoNewPrivileges=yes\n")
		b.WriteString("PrivateTmp=yes\n")
		b.WriteString("ProtectSystem=strict\n")
		b.WriteString("ProtectHome=read-only\n")
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", strings.Join(rwPaths(o), " "))
		b.WriteString("ProtectKernelTunables=yes\nProtectKernelModules=yes\nProtectControlGroups=yes\n")
		b.WriteString("RestrictSUIDSGID=yes\nLockPersonality=yes\n")
	} else {
		b.WriteString("Environment=TAILPROXY_USER_UNIT=1\n")
		b.WriteString("NoNewPrivileges=yes\n")
	}
	b.WriteString("\n[Install]\n")
	if o.UserUnit {
		b.WriteString("WantedBy=default.target\n")
	} else {
		b.WriteString("WantedBy=multi-user.target\n")
	}
	return b.String(), nil
}

// rwPaths returns the state dir and config dir, deduplicated and sorted.
func rwPaths(o UnitOptions) []string {
	set := map[string]bool{o.StateDir: true, filepath.Dir(o.Config): true}
	var out []string
	for p := range set {
		out = append(out, quoteArg(p))
	}
	sort.Strings(out)
	return out
}

// quoteArg quotes a path for a systemd command line if it contains spaces.
func quoteArg(s string) string {
	if strings.ContainsAny(s, " \t'") {
		return `"` + s + `"`
	}
	return s
}
