//go:build linux

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/NannaOlympicBroadcast/tailproxy/internal/panel"
	"github.com/NannaOlympicBroadcast/tailproxy/internal/relay"
	"github.com/NannaOlympicBroadcast/tailproxy/internal/service"
	"github.com/NannaOlympicBroadcast/tailproxy/internal/token"
)

const serviceUsage = `用法：
  tailproxy service install   [-c FILE] [--user] [--run-as USER] [--state-dir DIR] [--print] [--force]
  tailproxy service install   --relay [--listen ADDR] [--allow-private] [--run-as USER] [--state-dir DIR] [--print] [--force]
  tailproxy service uninstall [--user] [--relay]

install 生成 systemd 单元文件，执行 daemon-reload 和 enable --now（开机自启并立即启动），
然后打印面板地址和访问令牌。

  -c FILE          配置文件（默认 config.yaml，会转成绝对路径写进单元文件）
  --user           安装为用户服务（~/.config/systemd/user），并尝试 loginctl enable-linger
                   让它在开机时、无需登录就启动；默认安装为系统服务（需要 root）
  --run-as USER    系统服务以哪个用户运行（默认：sudo 调用者，否则 root）
  --state-dir DIR  状态目录（默认：运行用户的 ~/.lighthousepro）
  --print          只打印单元文件，不安装
  --force          覆盖不是由 tailproxy 生成的同名单元文件
  --relay          安装中继服务 tailproxy-relay.service（在 VPS 上运行 tailproxy relay，
                   在 tailscaled 之后启动）；--listen / --allow-private 同 tailproxy relay
`

const unitHeader = "# Generated by `tailproxy service install`."

func cmdService(args []string) error {
	if len(args) == 0 {
		fmt.Fprint(os.Stderr, serviceUsage)
		return errors.New("缺少子命令 install 或 uninstall")
	}
	switch args[0] {
	case "install":
		return serviceInstall(args[1:])
	case "uninstall":
		return serviceUninstall(args[1:])
	case "-h", "--help", "help":
		fmt.Print(serviceUsage)
		return nil
	}
	fmt.Fprint(os.Stderr, serviceUsage)
	return fmt.Errorf("未知子命令 %q", args[0])
}

func serviceInstall(args []string) error {
	fs := flag.NewFlagSet("service install", flag.ContinueOnError)
	fs.Usage = func() { fmt.Fprint(os.Stderr, serviceUsage) }
	cfg := fs.String("c", "config.yaml", "")
	userUnit := fs.Bool("user", false, "")
	runAs := fs.String("run-as", "", "")
	stateDir := fs.String("state-dir", "", "")
	printOnly := fs.Bool("print", false, "")
	force := fs.Bool("force", false, "")
	relayMode := fs.Bool("relay", false, "")
	listen := fs.String("listen", "", "")
	allowPrivate := fs.Bool("allow-private", false, "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if !*relayMode && (*listen != "" || *allowPrivate) {
		return errors.New("--listen / --allow-private 只用于 --relay")
	}
	if *relayMode && *listen != "" {
		if err := relay.CheckListenAddr(*listen); err != nil {
			return err
		}
	}

	exe, err := os.Executable()
	if err != nil {
		return err
	}
	if exe, err = filepath.EvalSymlinks(exe); err != nil {
		return err
	}
	var config string
	if !*relayMode {
		if config, err = filepath.Abs(*cfg); err != nil {
			return err
		}
		if _, err := os.Stat(config); err != nil {
			return fmt.Errorf("配置文件：%w", err)
		}
	}

	// Who runs the service, and therefore whose ~/.lighthousepro holds the token.
	var acct *user.User
	switch {
	case *userUnit:
		if *runAs != "" {
			return errors.New("--user 与 --run-as 不能同时使用")
		}
		acct, err = user.Current()
	case *runAs != "":
		acct, err = user.Lookup(*runAs)
	case os.Getenv("SUDO_USER") != "":
		acct, err = user.Lookup(os.Getenv("SUDO_USER"))
	default:
		acct, err = user.Current()
	}
	if err != nil {
		return err
	}
	if *stateDir == "" {
		*stateDir = filepath.Join(acct.HomeDir, service.DefaultDirName)
	}
	dir, err := filepath.Abs(*stateDir)
	if err != nil {
		return err
	}

	opts := service.UnitOptions{Exe: exe, Config: config, StateDir: dir, UserUnit: *userUnit,
		Relay: *relayMode, RelayListen: *listen, AllowPrivate: *allowPrivate}
	unitName := opts.Name()
	if !*userUnit {
		opts.User = acct.Username
	}
	unit, err := service.Unit(opts)
	if err != nil {
		return err
	}
	if *printOnly {
		fmt.Print(unit)
		return nil
	}

	if !*userUnit && os.Geteuid() != 0 {
		return errors.New("安装系统服务需要 root 权限：sudo tailproxy service install ...；或者用 --user 安装为用户服务")
	}
	unitPath, err := unitFilePath(*userUnit, unitName)
	if err != nil {
		return err
	}
	if old, err := os.ReadFile(unitPath); err == nil && !bytes.HasPrefix(old, []byte(unitHeader)) && !*force {
		return fmt.Errorf("%s 已存在且不是由 tailproxy 生成的；确认要覆盖请加 --force", unitPath)
	}

	paths := service.NewPaths(dir)
	if err := paths.Ensure(); err != nil {
		return err
	}
	var relayTok string
	if *relayMode {
		// Create the token now, so it can be printed below without the
		// service ever writing it to the journal.
		if relayTok, _, err = token.LoadOrCreate(paths.RelayToken); err != nil {
			return err
		}
	}
	if !*userUnit && acct.Uid != "0" {
		if err := chownTo(acct, dir); err != nil {
			return err
		}
	}
	if st, _ := paths.Running(); !*relayMode && st != nil && st.Manager != "systemd" {
		return fmt.Errorf("已有一个不由 systemd 管理的 tailproxy 在运行（pid %d），请先 tailproxy stop --state-dir %s", st.PID, dir)
	}

	if err := os.MkdirAll(filepath.Dir(unitPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(unitPath, []byte(unit), 0o644); err != nil {
		return err
	}
	fmt.Printf("已写入 %s\n", unitPath)

	ctl := systemctlArgs(*userUnit)
	for _, a := range [][]string{{"daemon-reload"}, {"enable", "--now", unitName}} {
		if out, err := exec.Command(ctl[0], append(ctl[1:], a...)...).CombinedOutput(); err != nil {
			return fmt.Errorf("%s %s 失败：%v\n%s", strings.Join(ctl, " "), strings.Join(a, " "), err, out)
		}
	}
	fmt.Printf("已启用开机自启并启动：%s enable --now %s\n", strings.Join(ctl, " "), unitName)

	if *userUnit {
		// Without lingering, user services only run while the user is logged in.
		if out, err := exec.Command("loginctl", "enable-linger", acct.Username).CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "警告：loginctl enable-linger %s 失败（%v）：%s\n  不启用 linger 时，用户服务只在你登录后才会启动。可以让管理员执行：sudo loginctl enable-linger %s\n",
				acct.Username, err, strings.TrimSpace(string(out)), acct.Username)
		} else {
			fmt.Printf("已执行 loginctl enable-linger %s：开机后无需登录即可启动\n", acct.Username)
		}
	}

	if *relayMode {
		// Type=notify: enable --now returned only after the relay listens.
		fmt.Printf("\ntailproxy relay %s（systemd 服务 %s）\n", version, unitName)
		fmt.Printf("  监听：%s（只接受 tailnet 内的连接）\n", relayListenDisplay(*listen))
		fmt.Printf("  令牌：%s\n", relayTok)
		fmt.Printf("  令牌保存在 %s，重启和开机后不变；查看：tailproxy relay token --state-dir %s\n", paths.RelayToken, dir)
		fmt.Printf("  在客户端面板「出口」页找到这台设备，点「添加为中继」并填入令牌\n\n")
		return nil
	}
	st, err := waitSystemdReady(paths, 30*time.Second)
	if err != nil {
		return fmt.Errorf("%w；查看日志：%s status %s 或 journalctl %s-u %s",
			err, strings.Join(ctl, " "), service.UnitName, map[bool]string{true: "--user ", false: ""}[*userUnit], service.UnitName)
	}
	printServiceBanner(st)
	return nil
}

func serviceUninstall(args []string) error {
	fs := flag.NewFlagSet("service uninstall", flag.ContinueOnError)
	fs.Usage = func() { fmt.Fprint(os.Stderr, serviceUsage) }
	userUnit := fs.Bool("user", false, "")
	relayMode := fs.Bool("relay", false, "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if !*userUnit && os.Geteuid() != 0 {
		return errors.New("卸载系统服务需要 root 权限：sudo tailproxy service uninstall")
	}
	unitName := service.UnitOptions{Relay: *relayMode}.Name()
	unitPath, err := unitFilePath(*userUnit, unitName)
	if err != nil {
		return err
	}
	old, err := os.ReadFile(unitPath)
	if errors.Is(err, os.ErrNotExist) {
		fmt.Printf("%s 不存在，无需卸载\n", unitPath)
		return nil
	}
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(old, []byte(unitHeader)) {
		return fmt.Errorf("%s 不是由 tailproxy 生成的，不会自动删除", unitPath)
	}
	ctl := systemctlArgs(*userUnit)
	if out, err := exec.Command(ctl[0], append(ctl[1:], "disable", "--now", unitName)...).CombinedOutput(); err != nil {
		return fmt.Errorf("%s disable --now %s 失败：%v\n%s", strings.Join(ctl, " "), unitName, err, out)
	}
	if err := os.Remove(unitPath); err != nil {
		return err
	}
	if out, err := exec.Command(ctl[0], append(ctl[1:], "daemon-reload")...).CombinedOutput(); err != nil {
		return fmt.Errorf("daemon-reload 失败：%v\n%s", err, out)
	}
	fmt.Printf("已停止并删除 %s。状态目录和令牌文件保留不动。\n", unitPath)
	return nil
}

func unitFilePath(userUnit bool, name string) (string, error) {
	if !userUnit {
		return filepath.Join("/etc/systemd/system", name), nil
	}
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		base = filepath.Join(home, ".config")
	}
	return filepath.Join(base, "systemd", "user", name), nil
}

func systemctlArgs(userUnit bool) []string {
	if userUnit {
		return []string{"systemctl", "--user"}
	}
	return []string{"systemctl"}
}

func chownTo(acct *user.User, dir string) error {
	uid, err := strconv.Atoi(acct.Uid)
	if err != nil {
		return err
	}
	gid, err := strconv.Atoi(acct.Gid)
	if err != nil {
		return err
	}
	if err := os.Chown(dir, uid, gid); err != nil {
		return err
	}
	// Token files created earlier by root must become readable by the
	// service account, or the service would refuse to start.
	p := service.NewPaths(dir)
	for _, tok := range []string{p.Token, p.RelayToken} {
		if fileExists(tok) {
			if err := os.Chown(tok, uid, gid); err != nil {
				return err
			}
		}
	}
	return nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// waitSystemdReady waits until the systemd-run instance has written its state.
func waitSystemdReady(paths service.Paths, timeout time.Duration) (*service.State, error) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if st, _ := paths.Running(); st != nil && st.Manager == "systemd" {
			return st, nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	return nil, fmt.Errorf("服务在 %s 内没有就绪", timeout)
}

// printServiceBanner prints the panel URL and token after installation. The
// token is read from the persisted file; it never goes through the journal.
func printServiceBanner(st *service.State) {
	fmt.Printf("\ntailproxy %s（systemd 服务，pid %d）\n", version, st.PID)
	fmt.Printf("  面板地址：%s\n", st.URL)
	switch {
	case st.TokenEnv != "":
		fmt.Printf("  访问令牌：来自环境变量 $%s（请在单元文件里用 Environment= 或 EnvironmentFile= 设置）\n\n", st.TokenEnv)
	case st.TokenFile != "":
		tok, err := panel.ReadTokenFile(st.TokenFile)
		if err != nil {
			fmt.Printf("  访问令牌：读取 %s 失败：%v\n\n", st.TokenFile, err)
			return
		}
		fmt.Printf("  访问令牌：%s\n", tok)
		fmt.Printf("  一键登录：%s#token=%s\n", st.URL, tok)
		fmt.Printf("  令牌持久化保存在 %s，重启和开机后不变\n\n", st.TokenFile)
	}
}
